name: DemonicChat
version: '${project.version}'
main: org.mrdarkimc.demonicchat.DemonicChat
api-version: '1.21'
commands:
  DemonicChat:
    description: "penis"
softdepend:
  - Vault
  - PlaceholdersAPI
