settings:
  enable-tag-mode: true
  default-chat-formatting: "" ##PAPI
  global-char: "!"
tag-builders:
  default: "*"
  local-chat: "prefix,playername,suffix,clan,message" #triggers without any symbol
  global-chat: "global,prefix,playername,suffix,clan,message" #triggers only with "global-char"
tags:
  global:
    text: "!"
    hover-event:
      text:
        - "&#94247AГлобальный чат"
        - "&#94247A! - для глобального чата"
    click-event:
      type: "OPEN_URL"
      #   OPEN_URL,
      #   OPEN_FILE,
      #   RUN_COMMAND,
      #   SUGGEST_COMMAND,
      #   CHANGE_PAGE,
      #   COPY_TO_CLIPBOARD
      output: "https://discord.gg/...."
  prefix:
    text: "%luckperms_prefix%"
    hover-event:
      text:
        - "&#94247AН&#95297Dа&#952E81ж&#963484м&#973987и&#973E8Aт&#98438Eе&#984891, &#9A5397ч&#9A589Bт&#9B5D9Eо &#9C67A5б&#9D6CA8ы &#9E77AEп&#9F7CB2о&#9F81B5с&#A086B8м&#A18CBCо&#A191BFт&#A296C2р&#A29BC5е&#A3A0C9т&#A4A5CCь &#A5B0D2п&#A6B5D6р&#A6BAD9о&#A7BFDCф&#A7C4E0и&#A8CAE3л&#A9CFE6ь &#AAD9EDи&#ABDEF0г&#ABE3F3р&#ACE9F6о&#ACEEFAк&#ADF3FDа"
        - "&#94247AБыстрая статистика: "
        - "&#94247AКлан: &#ADF3FD{clan}"
        - "&#94247AГруппа доната: &#ADF3FD%luckperms_prefix%"
    click-event:
      type: "RUN_COMMAND"
      output: "profile %player%"
  playername:
    text: "{playername}"
    hover-event:
      text:
        - "&#94247AН&#95297Dа&#952E81ж&#963484м&#973987и&#973E8Aт&#98438Eе&#984891, &#9A5397ч&#9A589Bт&#9B5D9Eо &#9C67A5б&#9D6CA8ы &#9E77AEп&#9F7CB2о&#9F81B5с&#A086B8м&#A18CBCо&#A191BFт&#A296C2р&#A29BC5е&#A3A0C9т&#A4A5CCь &#A5B0D2п&#A6B5D6р&#A6BAD9о&#A7BFDCф&#A7C4E0и&#A8CAE3л&#A9CFE6ь &#AAD9EDи&#ABDEF0г&#ABE3F3р&#ACE9F6о&#ACEEFAк&#ADF3FDа"
        - "&#94247AБыстрая статистика: "
        - "&#94247AКлан: &#ADF3FD{clan}"
        - "&#94247AГруппа доната: &#ADF3FD%luckperms_prefix%"
    click-event:
      type: "RUN_COMMAND"
      output: "profile %player%"
  suffix:
    text: "%luckperms_suffix%"
    hover-event:
      text:
        - "&#94247AН&#95297Dа&#952E81ж&#963484м&#973987и&#973E8Aт&#98438Eе&#984891, &#9A5397ч&#9A589Bт&#9B5D9Eо &#9C67A5б&#9D6CA8ы &#9E77AEп&#9F7CB2о&#9F81B5с&#A086B8м&#A18CBCо&#A191BFт&#A296C2р&#A29BC5е&#A3A0C9т&#A4A5CCь &#A5B0D2п&#A6B5D6р&#A6BAD9о&#A7BFDCф&#A7C4E0и&#A8CAE3л&#A9CFE6ь &#AAD9EDи&#ABDEF0г&#ABE3F3р&#ACE9F6о&#ACEEFAк&#ADF3FDа"
        - "&#94247AБыстрая статистика: "
        - "&#94247AКлан: &#ADF3FD{clan}"
        - "&#94247AГруппа доната: &#ADF3FD%luckperms_prefix%"
    click-event:
      type: "RUN_COMMAND"
      output: "profile %player%"
  clan:
    text: "{clan}"
    hover-event:
      text:
        - "&#94247AКлан: &#ADF3FD%clanname%"
        - "&#94247AКД клана: &#ADF3FD%clan_kd%"
        - ""
        - "&#94247AН&#95297Dа&#952E81ж&#963484м&#973987и&#973E8Aт&#98438Eе&#984891, &#9A5397ч&#9A589Bт&#9B5D9Eо &#9C67A5б&#9D6CA8ы &#9E77AEп&#9F7CB2о&#9F81B5с&#A086B8м&#A18CBCо&#A191BFт&#A296C2р&#A29BC5е&#A3A0C9т&#A4A5CCь &#A5B0D2п&#A6B5D6р&#A6BAD9о&#A7BFDCф&#A7C4E0и&#A8CAE3л&#A9CFE6ь &#AAD9EDи&#ABDEF0г&#ABE3F3р&#ACE9F6о&#ACEEFAк&#ADF3FDа"
    click-event:
      type: "RUN_COMMAND"
      output: "clan view %player%"
  message:
    text: "{message}"
    hover-event:
      text:
        - "&#ADF3FDНажмите, что бы зарепортить сообщение"
    click-event:
      type: "RUN_COMMAND"
      output: "report {player} {message} {time}"